### ISSUE TITLE
خطا در استفاده از تابع jmktime

### ISSUE THREAD

**Issue by vahidvalian** [hooman-pro/yii2-jdf#1]
با سلام و خسته نباشید

 در نسخه 7 php پارامتر is_dst در تابع اصلی mktime حذف شده با استفاده از تابع jmktime شاهد خطا هستیم

**Comment by hooman-mirghasemi** [comment]
سلام بررسی میکنم و در فرصت مناسب مشکل رو برطرف میکنم. ممنون از اطلاع دادنتون.
